name: ci

on: [push]

jobs:
  build:
    name: ${{ matrix.kind }} ${{ matrix.os }} ${{matrix.node}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest]
        node: ['14']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: NPM step
        run: |
          npm install
          npm run docs:build

      - name: Push
        run: |
          cd docs/.vuepress/dist
          git init
          git add -A
          git config --local user.email "tsingwoong@163.com"
          git config --local user.name "tsingwong"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit -m "update by github action"
          git push -f master:gh-pages
