name: ci

on: [push]

jobs:
  build:
    name: ${{ matrix.kind }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Build and Deploy
        uses: tsingwong/vuepress-deploy-test@master
        env:
          TARGET_REPO: tsingwong/vuepress-deploy-test
          TARGET_BRANCH: gh_pages
          BUILD_SCRIPT: yarn && yarn docs:build
          BUILD_DIR: doc/.vuepress/dist/
